name: Buildorder

on:
  push:
    branches:
    - '*'
    paths:
    - 'packages/**'
    - 'root-packages/**'
    - 'x11-packages/**'
    - 'scripts/buildorder.py'
    - 'scripts/test_buildorder.py'
  pull_request:
    paths:
    - 'packages/**'
    - 'root-packages/**'
    - 'x11-packages/**'
    - 'scripts/buildorder.py'
    - 'scripts/test_buildorder.py'
  workflow_dispatch:

permissions: {}

jobs:
  check-buildorder:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run buildorder tests
      run: ./scripts/test_buildorder.py
    - name: Check consistency with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "scripts/buildorder.py scripts/test_buildorder.py"
    - name: Check buildorder
      run: ./scripts/buildorder.py
